### ISSUE TITLE
Need to add README

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [datopian/ckanext-vocabulary#1]
We need to add a README containing the instructions for usage and the functionality provided by the extension

## Acceptance

* [x] Complete instructions are present in the README of the repo

## Tasks

* [x] Add the extension description including the features and functionality
* [ ] Installation/Dependency instructions (if any)
...

**Comment by ismail-shahzad** [comment]
**FIXED**

Closing this as fixed. Readme has been added.
